### ISSUE TITLE
[BUG] Detections and Alerts is no more a 'Beta' feature for 7.10

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/security-docs#393]
**Description**: Detections and Alerts is no more a 'Beta' feature for 7.10

**Observation**: Both heading and screenshot need to be updated as both show Detections and Alerts as a 'Beta' feature.

**Note**: Same behavior is seen for Detection Rules.

**URL link or topic name**: 
- [Detections and Alerts (beta)](https://www.elastic.co/guide/en/security/current/detection-engine-overview.html)
- [Creating detection rules](https://www.elastic.co/guide/en/security/current/rules-ui-create.html)

**Screenshots**:
- Screenshot in doc:
![docBetaFeature](https://user-images.githubusercontent.com/60252716/100996484-1be45680-357f-11eb-9d34-73425d8221ba.png)

- UI screenshot:
![UIBetaFeature](https://user-images.githubusercontent.com/60252716/100996476-1ab32980-357f-11eb-8f39-b51e82922b89.png)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource Please review!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @jmikell821

**Comment by jmikell821** [comment]
Fixed in #411.

**Comment by muskangulati-qasource** [comment]
Hi @jmikell821,

We validated the docs and found that the issue is **partially fixed**.

- [Detections and Alerts](https://www.elastic.co/guide/en/security/current/detection-engine-overview.html) : 🟢 Fixed
![394](https://user-images.githubusercontent.com/60252716/104287121-021e2380-54dc-11eb-9ef3-48c289a6c3d7.PNG)

- [Creating detection rules](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#rules-ui-create) : 🔴 Not Fixed
![394_](https://user-images.githubusercontent.com/60252716/104287175-15c98a00-54dc-11eb-8f67-47af2c138b69.PNG)

Hence, reopening this issue.

Thanks!!

**Comment by jmikell821** [comment]
Should be fixed in 7.11.

**Comment by muskangulati-qasource** [comment]
Hi @jmikell821,

We validated the docs and found that the issue is now **fixed**.

**[Creating detection rules](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#rules-ui-create)**: 🟢**Fixed**

**Refer Screenshot**:
![Rules](https://user-images.githubusercontent.com/60252716/107633777-8fe16000-6c8e-11eb-89f5-b28b4e6e6d25.PNG)

Thanks!!
